name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      shell: cmd
      run: docker build -t evandroamparo/delphi2007-build:latest .
      
    - name: Publish the Docker image
      run: |
        docker login -u evandroamparo -p ${{ secrets.DOCKER_PASSWORD }}
        docker push evandroamparo/delphi2007-build:latest .
